name: FrontEnd Build
on:
  push:
    branches:
      - main
    paths:
      - "app/node_project/"
      - ".github/workflows/build.yml"
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    if: ( startsWith(github.head_ref, 'FE_') && github.event.pull_request.merged == false ) || ( github.event_name == 'push' )
    name: SonarCloud
    runs-on: ubuntu-latest
    timeout-minutes: 8
    defaults:
      run:
        working-directory: app/node_project
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ github.workspace }}/app/client/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - name: Install Node.js 20.11.1
        uses: actions/setup-node@v2
        with:
          node-version: "20.11.1"
  
      - name: Install the dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm install
      - name: Test and coverage
        run: npm test 
      - name: SonarCloud Scan
        with:
          projectBaseDir: app/node_project
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
