name: FrontEnd Build
on:
  push:
    branches:
      - main
    paths:
      - "app/client/**"
      - ".github/workflows/build.yml"
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    if: ( startsWith(github.head_ref, 'FE_') && github.event.pull_request.merged == false ) || ( github.event_name == 'push' )
    name: SonarCloud
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: app/client/
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ${{ github.workspace }}/frontend/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Test and coverage
        run: npm test
      - name: SonarCloud Scan
        with:
          projectBaseDir: app/client
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
